CREATE DATABASE IF NOT EXISTS bmw_grid;
USE bmw_grid;

CREATE TABLE IF NOT EXISTS records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  payload JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SHOW DATABASES;
USE bmw_grid;
SHOW TABLES;
DESCRIBE records;